import React, { useState } from 'react';
import { JournalEntry } from '../types';
import { ArrowDownRight, ArrowUpRight, Download, FileSpreadsheet, FileText, AlertTriangle } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

interface JournalTableProps {
  entries: JournalEntry[];
  onReset: () => void;
  profile: any;
}

export const JournalTable: React.FC<JournalTableProps> = ({ entries, onReset, profile }) => {
  const [showResetConfirm, setShowResetConfirm] = useState(false);
  
  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR' }).format(amount);
  };

  const exportToCSV = () => {
    const headers = ['Tanggal', 'Keterangan', 'Akun Debit', 'Akun Kredit', 'Nominal', 'Kategori'];
    const rows = entries.map(e => [
      e.date,
      `"${e.description}"`,
      e.debitAccount,
      e.creditAccount,
      e.amount,
      e.category
    ]);
    
    const csvContent = "data:text/csv;charset=utf-8," 
      + [headers.join(','), ...rows.map(e => e.join(','))].join('\n');
      
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `Jurnal_Umum_SiJO_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const exportToExcel = () => {
    const worksheet = XLSX.utils.json_to_sheet(entries.map(e => ({
      Tanggal: e.date,
      Keterangan: e.description,
      Ref: e.category,
      Debit: e.debitAccount,
      Kredit: e.creditAccount,
      Nominal: e.amount
    })));
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "Jurnal Umum");
    XLSX.writeFile(workbook, `Jurnal_Umum_SiJO_${new Date().toISOString().split('T')[0]}.xlsx`);
  };

  const exportToPDF = () => {
    // Inisialisasi jsPDF
    const doc = new jsPDF();

    // -- Header Design --
    // Background Header Blue
    doc.setFillColor(14, 165, 233); // Primary-500
    doc.rect(0, 0, 210, 40, 'F');

    // Title text White
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text("Laporan Jurnal Umum", 14, 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text("Generated by SiJO (Sistem Jurnal Otomatis)", 14, 28);

    // Profile Info in Header (Right side)
    doc.setFontSize(10);
    doc.text(profile.name || "User", 196, 18, { align: 'right' });
    doc.text(profile.university || "Universitas", 196, 24, { align: 'right' });
    doc.text(new Date().toLocaleDateString('id-ID'), 196, 30, { align: 'right' });

    // -- Content Info --
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text("Ringkasan Transaksi", 14, 50);

    // -- Table Data Preparation --
    const tableColumn = ["Tanggal", "Keterangan", "Akun Debit", "Akun Kredit", "Nominal (IDR)"];
    const tableRows: any[] = [];

    entries.forEach(entry => {
      const entryData = [
        entry.date,
        entry.description,
        entry.debitAccount,
        entry.creditAccount,
        formatCurrency(entry.amount)
      ];
      tableRows.push(entryData);
    });

    // -- Generate Table --
    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 55,
      theme: 'grid',
      headStyles: { 
        fillColor: [14, 165, 233], 
        textColor: 255,
        fontStyle: 'bold' 
      },
      styles: {
        fontSize: 9,
        cellPadding: 3,
      },
      alternateRowStyles: {
        fillColor: [240, 249, 255]
      },
      columnStyles: {
        0: { cellWidth: 25 },
        1: { cellWidth: 'auto' }, 
        4: { halign: 'right' }
      }
    });

    // -- Footer --
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Dokumen ini dihasilkan secara otomatis oleh sistem SiJO.", 105, pageHeight - 10, { align: 'center' });

    doc.save(`Laporan_Jurnal_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <div className="space-y-6 animate-fade-in pb-10 relative">
      {/* Reset Confirmation Modal */}
      {showResetConfirm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4 animate-fade-in">
           <div className="bg-white rounded-xl shadow-2xl max-w-md w-full overflow-hidden border border-slate-200 transform transition-all scale-100">
              <div className="p-6">
                 <div className="flex items-start gap-4">
                    <div className="p-3 bg-red-100 rounded-full shrink-0 text-red-600">
                       <AlertTriangle size={24} />
                    </div>
                    <div>
                       <h3 className="text-lg font-bold text-slate-900">Mulai Input Baru?</h3>
                       <p className="text-sm text-slate-600 mt-2 leading-relaxed">
                          Tindakan ini akan <strong>menghapus seluruh data jurnal</strong> yang sedang aktif saat ini.
                          <br/><br/>
                          Pastikan Anda sudah menyimpan atau <strong>mengunduh laporan (PDF/Excel)</strong> sebelum melanjutkan.
                       </p>
                    </div>
                 </div>
              </div>
              <div className="bg-slate-50 px-6 py-4 flex justify-end gap-3 border-t border-slate-100">
                 <button
                    onClick={() => setShowResetConfirm(false)}
                    className="px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-200 rounded-lg transition-colors"
                 >
                    Batal
                 </button>
                 <button
                    onClick={() => {
                      setShowResetConfirm(false);
                      onReset();
                    }}
                    className="px-4 py-2 text-sm font-bold text-white bg-red-600 hover:bg-red-700 rounded-lg transition-colors shadow-sm"
                 >
                    Ya, Hapus & Buat Baru
                 </button>
              </div>
           </div>
        </div>
      )}

      <div className="flex flex-col xl:flex-row justify-between items-start xl:items-center gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-800">Laporan Jurnal Umum</h2>
          <p className="text-slate-500">Hasil pemrosesan transaksi periode berjalan</p>
        </div>
        <div className="flex flex-wrap gap-2 w-full xl:w-auto">
          <button 
            onClick={() => setShowResetConfirm(true)}
            className="flex-1 xl:flex-none px-4 py-2 text-sm font-medium text-slate-600 bg-white border border-slate-300 rounded-lg hover:bg-red-50 hover:text-red-600 hover:border-red-200 transition-all"
          >
            Input Baru
          </button>
          
          <div className="flex gap-2 flex-1 xl:flex-none">
            <button 
              onClick={exportToCSV}
              className="flex-1 flex items-center justify-center gap-2 px-3 py-2 text-sm font-medium text-slate-700 bg-white border border-slate-300 rounded-lg hover:bg-slate-50 transition-colors"
              title="Download CSV"
            >
              <Download size={16} /> <span className="hidden sm:inline">CSV</span>
            </button>
            
            <button 
              onClick={exportToExcel}
              className="flex-1 flex items-center justify-center gap-2 px-3 py-2 text-sm font-medium text-white bg-emerald-600 rounded-lg hover:bg-emerald-700 transition-colors shadow-sm"
              title="Download Excel"
            >
              <FileSpreadsheet size={16} /> <span className="hidden sm:inline">Excel</span>
            </button>

            <button 
              onClick={exportToPDF}
              className="flex-1 flex items-center justify-center gap-2 px-3 py-2 text-sm font-medium text-white bg-red-600 rounded-lg hover:bg-red-700 transition-colors shadow-sm"
              title="Download PDF"
            >
              <FileText size={16} /> <span className="hidden sm:inline">PDF</span>
            </button>
          </div>
        </div>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="text-xs text-slate-500 uppercase bg-slate-50 border-b border-slate-200">
              <tr>
                <th className="px-6 py-4 font-semibold">Tanggal</th>
                <th className="px-6 py-4 font-semibold">Keterangan Transaksi</th>
                <th className="px-6 py-4 font-semibold text-center">Ref</th>
                <th className="px-6 py-4 font-semibold">Akun Debit</th>
                <th className="px-6 py-4 font-semibold">Akun Kredit</th>
                <th className="px-6 py-4 font-semibold text-right">Nominal (IDR)</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {entries.map((entry) => (
                <tr key={entry.id} className="hover:bg-slate-50/50 transition-colors">
                  <td className="px-6 py-4 font-medium text-slate-900 whitespace-nowrap">
                    {entry.date}
                  </td>
                  <td className="px-6 py-4 text-slate-600 max-w-xs truncate" title={entry.description}>
                    <div className="flex flex-col">
                      <span>{entry.description}</span>
                      <span className="text-xs text-slate-400 mt-0.5 inline-block px-2 py-0.5 bg-slate-100 rounded-full w-fit">
                        {entry.category}
                      </span>
                    </div>
                  </td>
                  <td className="px-6 py-4 text-center">
                    <div className="flex flex-col items-center gap-1">
                      {/* Debit Indicator */}
                      <div className="flex items-center text-emerald-600 text-xs font-bold bg-emerald-50 px-2 py-0.5 rounded">
                        <ArrowDownRight size={12} className="mr-1" /> Db
                      </div>
                      {/* Credit Indicator */}
                      <div className="flex items-center text-red-600 text-xs font-bold bg-red-50 px-2 py-0.5 rounded">
                         <ArrowUpRight size={12} className="mr-1" /> Kr
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <span className="font-semibold text-slate-800">{entry.debitAccount}</span>
                  </td>
                  <td className="px-6 py-4">
                    <span className="font-semibold text-slate-800">{entry.creditAccount}</span>
                  </td>
                  <td className="px-6 py-4 text-right font-mono font-medium text-slate-700">
                    {formatCurrency(entry.amount)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};